"""FLOP accounting for the matched-compute comparison (concept vs. tokens).

Factor convention (standard Kaplan/Chinchilla):
- A parameter in a matmul costs ~2 FLOPs per position in the forward (multiply-add).
- Training with TRAINABLE weights: forward 2ND + backward 4ND = **6ND**
  (2ND for input grad, 2ND for weight grad).
- FROZEN module in the graph (e.g. the SONAR decoder in propagated CE): forward 2ND
  + backward for input grad ONLY 2ND = **4ND** (no weight grad computed).
- Inference (with KV-cache, per generated position): **2ND**.

N = parameters participating in matmuls (excludes embedding tables, which are lookups).
D = number of positions processed (tokens for the token model; concepts for the
    ConceptTransformer; tokens for the SONAR decoder/encoder).

The CRITICAL fairness point: to compute its loss the concept model invokes the frozen
SONAR decoder (~large N_dec). Ignoring that cost unfairly favors the concept model.
This module counts it explicitly.
"""
from dataclasses import dataclass


@dataclass
class FlopBreakdown:
    concept_transformer: float = 0.0
    sonar_decoder: float = 0.0
    sonar_encoder_amortized: float = 0.0
    token_transformer: float = 0.0

    @property
    def total(self) -> float:
        return (self.concept_transformer + self.sonar_decoder
                + self.sonar_encoder_amortized + self.token_transformer)

    def as_dict(self) -> dict:
        return {"concept_transformer": self.concept_transformer,
                "sonar_decoder": self.sonar_decoder,
                "sonar_encoder_amortized": self.sonar_encoder_amortized,
                "token_transformer": self.token_transformer,
                "total": self.total}


def concept_training_flops(n_ct: int, n_dec: int, n_enc: int, n_concepts: int,
                           tokens_per_concept: float, n_epochs: float) -> FlopBreakdown:
    """FLOPs to train the concept model over `n_concepts` concepts, `n_epochs` times.

    - ConceptTransformer (trainable): 6 · N_ct · (concepts processed).
    - SONAR decoder (frozen, teacher forcing over each concept's tokens):
      4 · N_dec · (tokens decoded).
    - SONAR encoder (frozen, paid ONCE to build the dataset, amortized):
      2 · N_enc · (corpus tokens) / n_epochs  → returns the total encode cost divided
      by epochs (the per-epoch cost).
    """
    concepts_processed = n_concepts * n_epochs
    tokens_decoded = concepts_processed * tokens_per_concept
    corpus_tokens = n_concepts * tokens_per_concept
    return FlopBreakdown(
        concept_transformer=6 * n_ct * concepts_processed,
        sonar_decoder=4 * n_dec * tokens_decoded,
        sonar_encoder_amortized=2 * n_enc * corpus_tokens,  # total encode (once)
    )


def token_training_flops(n_tt: int, n_concepts: int, tokens_per_concept: float,
                         n_epochs: float) -> FlopBreakdown:
    """FLOPs to train the token baseline over the SAME text (same tokens).
    6 · N_tt · (tokens processed). N_tt includes blocks + LM head (d×vocab matmul),
    excludes the embedding table (lookup).
    """
    tokens_processed = n_concepts * tokens_per_concept * n_epochs
    return FlopBreakdown(token_transformer=6 * n_tt * tokens_processed)


def concept_inference_flops_per_token(n_ct: int, n_dec: int, tokens_per_concept: float) -> float:
    """FLOPs per GENERATED token at inference (short generation).
    Per concept: 2·N_ct (predict the embedding) + 2·N_dec·L_tok (decode it).
    Per token: 2·N_ct/L_tok + 2·N_dec.
    """
    return 2 * n_ct / tokens_per_concept + 2 * n_dec


def token_inference_flops_per_token(n_tt: int) -> float:
    """FLOPs per token generated by the token baseline (with KV-cache): 2·N_tt."""
    return 2 * n_tt


def context_processing_flops(n_model: int, n_positions: int, dim: int) -> float:
    """FLOPs to PROCESS a context of `n_positions` positions (prefill), including the
    quadratic attention term. 2·N·P (matmuls) + 2·(P²·dim) (QK^T and AV attention).
    This is the concept model's edge: it compresses the context ~L_tok×, so
    P_concepts = P_tokens / L_tok, shrinking both the linear and quadratic terms.
    """
    return 2 * n_model * n_positions + 2 * (n_positions ** 2) * dim


def concept_graph_training_flops(n_ct: int, n_gdec: int, n_enc: int, n_concepts: int,
                                 tokens_per_concept: float, n_epochs: float) -> FlopBreakdown:
    """Concept model with GraphDecoder (trainable, NON-autoregressive).
    Key: the graph decoder is O(1) in length (K fixed nodes), so its per-concept cost is
    6·N_gdec (one pass), WITHOUT the L_tok factor that penalizes the text decoder.
    """
    concepts_processed = n_concepts * n_epochs
    corpus_tokens = n_concepts * tokens_per_concept
    return FlopBreakdown(
        concept_transformer=6 * n_ct * concepts_processed,
        sonar_decoder=6 * n_gdec * concepts_processed,   # trainable graph decoder, O(1)
        sonar_encoder_amortized=2 * n_enc * corpus_tokens,
    )


def concept_graph_inference_flops_per_concept(n_ct: int, n_gdec: int) -> float:
    """FLOPs per CONCEPT generated with GraphDecoder: 2·N_ct + 2·N_gdec (one pass)."""
    return 2 * n_ct + 2 * n_gdec


def token_graph_extraction_flops_per_concept(n_tt: int, serialized_graph_tokens: float,
                                             train: bool = False) -> float:
    """Token baseline extracting the graph: generates the SERIALIZED graph (triples as
    text) autoregressively. Cost = (6 if train else 2)·N_tt·(serialized tokens)."""
    factor = 6 if train else 2
    return factor * n_tt * serialized_graph_tokens


def flops_summary(n_ct, n_dec, n_enc, n_tt, n_concepts, tokens_per_concept, n_epochs) -> dict:
    """Full comparative report for a given budget."""
    ct = concept_training_flops(n_ct, n_dec, n_enc, n_concepts, tokens_per_concept, n_epochs)
    tt = token_training_flops(n_tt, n_concepts, tokens_per_concept, n_epochs)
    return {
        "training_flops": {
            "concept_model": ct.as_dict(),
            "token_model": tt.as_dict(),
            "ratio_concept_over_token": ct.total / tt.total if tt.total else None,
        },
        "inference_flops_per_generated_token": {
            "concept_model": concept_inference_flops_per_token(n_ct, n_dec, tokens_per_concept),
            "token_model": token_inference_flops_per_token(n_tt),
        },
        "params": {"n_ct": n_ct, "n_dec": n_dec, "n_enc": n_enc, "n_tt": n_tt},
        "assumptions": {"n_concepts": n_concepts, "tokens_per_concept": tokens_per_concept,
                        "n_epochs": n_epochs},
    }
