"""FLOP accounting for the matched-compute comparison (concept vs. tokens).

Factor convention (standard Kaplan/Chinchilla):
- A parameter in a matmul costs ~2 FLOPs per position in the forward (multiply-add).
- Training with TRAINABLE weights: forward 2ND + backward 4ND = **6ND**
  (2ND for input grad, 2ND for weight grad).
- FROZEN module in the graph (e.g. the SONAR decoder in propagated CE): forward 2ND
  + backward for input grad ONLY 2ND = **4ND** (no weight grad computed).
- Inference (with KV-cache, per generated position): **2ND**.

N = parameters participating in matmuls (excludes embedding tables, which are lookups).
D = number of positions processed (tokens for the token model; concepts for the
    ConceptTransformer; tokens for the SONAR decoder/encoder).

The CRITICAL fairness point: to compute its loss the concept model invokes the frozen
SONAR decoder (~large N_dec). Ignoring that cost unfairly favors the concept model.
This module counts it explicitly.
"""
from dataclasses import dataclass


@dataclass
class FlopBreakdown:
    concept_transformer: float = 0.0
    sonar_decoder: float = 0.0
    sonar_encoder_amortized: float = 0.0
    token_transformer: float = 0.0

    @property
    def total(self) -> float:
        return (self.concept_transformer + self.sonar_decoder
                + self.sonar_encoder_amortized + self.token_transformer)

    def as_dict(self) -> dict:
        return {"concept_transformer": self.concept_transformer,
                "sonar_decoder": self.sonar_decoder,
                "sonar_encoder_amortized": self.sonar_encoder_amortized,
                "token_transformer": self.token_transformer,
                "total": self.total}


def concept_training_flops(n_ct: int, n_dec: int, n_enc: int, n_concepts: int,
                           tokens_per_concept: float, n_epochs: float) -> FlopBreakdown:
    """FLOPs to train the concept model over `n_concepts` concepts, `n_epochs` times.

    - ConceptTransformer (trainable): 6 · N_ct · (concepts processed).
    - SONAR decoder (frozen, teacher forcing over each concept's tokens):
      4 · N_dec · (tokens decoded).
    - SONAR encoder (frozen, paid ONCE to build the dataset, amortized):
      2 · N_enc · (corpus tokens) / n_epochs  → returns the total encode cost divided
      by epochs (the per-epoch cost).
    """
    concepts_processed = n_concepts * n_epochs
    tokens_decoded = concepts_processed * tokens_per_concept
    corpus_tokens = n_concepts * tokens_per_concept
    return FlopBreakdown(
        concept_transformer=6 * n_ct * concepts_processed,
        sonar_decoder=4 * n_dec * tokens_decoded,
        sonar_encoder_amortized=2 * n_enc * corpus_tokens,  # total encode (once)
    )


def token_training_flops(n_tt: int, n_concepts: int, tokens_per_concept: float,
                         n_epochs: float) -> FlopBreakdown:
    """FLOPs to train the token baseline over the SAME text (same tokens).
    6 · N_tt · (tokens processed). N_tt includes blocks + LM head (d×vocab matmul),
    excludes the embedding table (lookup).
    """
    tokens_processed = n_concepts * tokens_per_concept * n_epochs
    return FlopBreakdown(token_transformer=6 * n_tt * tokens_processed)


def concept_inference_flops_per_token(n_ct: int, n_dec: int, tokens_per_concept: float) -> float:
    """FLOPs per GENERATED token at inference (short generation).
    Per concept: 2·N_ct (predict the embedding) + 2·N_dec·L_tok (decode it).
    Per token: 2·N_ct/L_tok + 2·N_dec.
    """
    return 2 * n_ct / tokens_per_concept + 2 * n_dec


def token_inference_flops_per_token(n_tt: int) -> float:
    """FLOPs per token generated by the token baseline (with KV-cache): 2·N_tt."""
    return 2 * n_tt


def context_processing_flops(n_model: int, n_positions: int, dim: int) -> float:
    """FLOPs to PROCESS a context of `n_positions` positions (prefill), including the
    quadratic attention term. 2·N·P (matmuls) + 2·(P²·dim) (QK^T and AV attention).
    This is the concept model's edge: it compresses the context ~L_tok×, so
    P_concepts = P_tokens / L_tok, shrinking both the linear and quadratic terms.
    """
    return 2 * n_model * n_positions + 2 * (n_positions ** 2) * dim


def concept_graph_training_flops(n_ct: int, n_gdec: int, n_enc: int, n_concepts: int,
                                 tokens_per_concept: float, n_epochs: float) -> FlopBreakdown:
    """Concept model with GraphDecoder (trainable, NON-autoregressive).
    Key: the graph decoder is O(1) in length (K fixed nodes), so its per-concept cost is
    6·N_gdec (one pass), WITHOUT the L_tok factor that penalizes the text decoder.
    """
    concepts_processed = n_concepts * n_epochs
    corpus_tokens = n_concepts * tokens_per_concept
    return FlopBreakdown(
        concept_transformer=6 * n_ct * concepts_processed,
        sonar_decoder=6 * n_gdec * concepts_processed,   # trainable graph decoder, O(1)
        sonar_encoder_amortized=2 * n_enc * corpus_tokens,
    )


def concept_graph_inference_flops_per_concept(n_ct: int, n_gdec: int) -> float:
    """FLOPs per CONCEPT generated with GraphDecoder: 2·N_ct + 2·N_gdec (one pass)."""
    return 2 * n_ct + 2 * n_gdec


def token_graph_extraction_flops_per_concept(n_tt: int, serialized_graph_tokens: float,
                                             train: bool = False) -> float:
    """Token baseline extracting the graph: generates the SERIALIZED graph (triples as
    text) autoregressively. Cost = (6 if train else 2)·N_tt·(serialized tokens)."""
    factor = 6 if train else 2
    return factor * n_tt * serialized_graph_tokens


def flops_summary(n_ct, n_dec, n_enc, n_tt, n_concepts, tokens_per_concept, n_epochs) -> dict:
    """Full comparative report for a given budget."""
    ct = concept_training_flops(n_ct, n_dec, n_enc, n_concepts, tokens_per_concept, n_epochs)
    tt = token_training_flops(n_tt, n_concepts, tokens_per_concept, n_epochs)
    return {
        "training_flops": {
            "concept_model": ct.as_dict(),
            "token_model": tt.as_dict(),
            "ratio_concept_over_token": ct.total / tt.total if tt.total else None,
        },
        "inference_flops_per_generated_token": {
            "concept_model": concept_inference_flops_per_token(n_ct, n_dec, tokens_per_concept),
            "token_model": token_inference_flops_per_token(n_tt),
        },
        "params": {"n_ct": n_ct, "n_dec": n_dec, "n_enc": n_enc, "n_tt": n_tt},
        "assumptions": {"n_concepts": n_concepts, "tokens_per_concept": tokens_per_concept,
                        "n_epochs": n_epochs},
    }


# ---------------------------------------------------------------------------
# Memory-bandwidth roofline (arithmetic intensity)
#
# A FLOP advantage only materializes if the kernel is compute-bound, not
# bandwidth-bound. The counter-argument to the 1074x claim: a ~5.8M decoder
# has low arithmetic intensity, so serving spends time moving weights, not
# computing. This is answered numerically, not rhetorically:
#
#   1. Weight bandwidth amortizes over the batch. Weights load once per
#      forward; activations scale with B. AI(B) = B*F / (W + B*A) rises from
#      a memory-bound point at B=1 to a ceiling F/A as B grows. B_amort = W/A
#      is ~19-25 here, so at server batch (B>=256) weights are <3% of traffic
#      and the "tiny weights reload" objection is void.
#   2. Non-autoregressive => no KV cache. Per-user memory footprint beyond the
#      shared weights is ~0, so B reaches thousands (measured: B=1024 -> 6.7 GB).
#      The autoregressive baseline spends most VRAM on per-user KV cache, which
#      both caps concurrency and *is* the bandwidth it streams every step.
#   3. The comparison target is memory-bound by nature. Autoregressive text
#      decoding moves 605M weights (or streams KV) once PER GENERATED TOKEN over
#      L_tok steps; the graph decoder moves ~5.8M once. "Memory-bound" is the
#      regime AR decoding suffers in; a KV-free single pass is the mitigation.
#
# Firm number: RTX 5070 HBM bandwidth 672 GB/s (192-bit GDDR7 @ 28 Gbps).
# Compute peak is quoted as a range because the exact BF16 tensor peak is
# not authoritatively published; conclusions are stated against the range.
# ---------------------------------------------------------------------------

RTX5070_BW_BYTES_S = 672e9
RTX5070_PEAKS_FLOPS = {          # FLOP/s, labeled by confidence
    "fp32_cuda": 30.9e12,        # conservative lower bound (CUDA cores)
    "bf16_tensor_mid": 123e12,   # mid estimate
    "bf16_tensor_high": 247e12,  # aggressive upper bound
}


def graph_decoder_flops_bytes(K: int, d: int, V: int, R: int, concept_dim: int = 1024,
                              w_bytes: int = 2, a_bytes: int = 2) -> dict:
    """Per-sample forward FLOPs, activation traffic, and weight bytes for a
    GraphDecoder (K nodes, node_dim d, label vocab V, R relations). Bilinear
    adjacency is two matmuls: (n_i^T W_r) then (.)n_j. w_bytes/a_bytes default
    to bf16 (2)."""
    params = (concept_dim * K * d + K * d) + (d + 1) + (d * V + V) + (R * d * d)
    flops = (2 * concept_dim * K * d + 2 * K * d + 2 * K * d * V
             + 2 * R * K * d * d + 2 * R * K * K * d)
    act_floats = (concept_dim + 2 * K * d + K + K * V + 2 * R * K * d + R * K * K)
    return {"params": params, "flops_per_sample": flops,
            "act_bytes_per_sample": act_floats * a_bytes, "weight_bytes": params * w_bytes}


def arithmetic_intensity(stats: dict, batch: int) -> float:
    """AI(B) = B*F / (W + B*A) FLOP/byte. Weights loaded once, activations per sample."""
    return (batch * stats["flops_per_sample"]) / (
        stats["weight_bytes"] + batch * stats["act_bytes_per_sample"])


def weight_traffic_fraction(stats: dict, batch: int) -> float:
    """Fraction of memory traffic spent (re)loading weights at batch B. -> 0 as B grows."""
    w = stats["weight_bytes"]
    return w / (w + batch * stats["act_bytes_per_sample"])


def roofline_crossover_batch(stats: dict, peak_flops: float,
                             bw_bytes_s: float = RTX5070_BW_BYTES_S) -> float:
    """Batch B* where AI(B*) meets the ridge point peak/BW (compute-bound above it).
    inf if the AI ceiling F/A never reaches the ridge (memory-bound at any B)."""
    ridge = peak_flops / bw_bytes_s
    denom = stats["flops_per_sample"] - ridge * stats["act_bytes_per_sample"]
    return ridge * stats["weight_bytes"] / denom if denom > 0 else float("inf")


# ---------------------------------------------------------------------------
# The encoder toll ("the KV-cache cost merely moved to the encoder side")
#
# Factual basis: the SONAR text encoder is NOT autoregressive. It is a single
# parallel transformer pass over the source tokens followed by pooling: cost
# 2*N_enc per token, ONCE per text. The proper comparison is against the token
# LM's own prefill, which every serving stack also pays: 2*N_tt per token over
# the same tokens, plus quadratic attention. The encoder is the prefill analog,
# not an extra toll — and its output (1024 floats per sentence) is a cacheable
# artifact reusable across every later generation step and every session,
# whereas KV caches are per-session, per-layer, and evicted under pressure.
# ---------------------------------------------------------------------------

def sonar_encoder_prefill_flops(n_tokens: int, n_enc: int = 504_000_000) -> float:
    """One-time encode cost of a context: 2*N_enc per token, single parallel pass."""
    return 2.0 * n_enc * n_tokens


def concept_context_state_bytes(n_tokens: int, tokens_per_concept: float = 25.0,
                                concept_dim: int = 1024, bytes_per_float: int = 2) -> float:
    """Per-user resident context state for the concept stack: one embedding per
    sentence. This is the whole 'cache' — no per-layer, per-token KV."""
    return (n_tokens / tokens_per_concept) * concept_dim * bytes_per_float


def token_kv_cache_bytes(n_tokens: int, n_layers: int, dim: int,
                         bytes_per_float: int = 2) -> float:
    """Per-user KV cache of a standard decoder-only LM: K and V per layer per token."""
    return n_tokens * 2 * n_layers * dim * bytes_per_float


# ---------------------------------------------------------------------------
# Hybrid copy-channel collapse threshold
#
# If a fraction f of concepts falls back to an autoregressive copy channel
# (long open-vocab literals), mean latency is (1-f)*t_graph + f*t_copy and the
# aggregate speedup vs the 605M text decoder decays. copy_fraction_ceiling
# gives the largest f that still preserves a target speedup. The measured
# non-AR alternative (exp017 char-grid: chars as ordered node slots, one pass,
# 0.0048 ms at K=32) is CHEAPER than an AR fallback by construction and keeps
# the ceiling from binding for closed-alphabet literals (hex, UUID, digits).
# ---------------------------------------------------------------------------

SONAR_TEXT_DECODE_MS = 13.96      # measured, exp011
GRAPH_DECODE_MS = 0.013           # measured, exp011 (medium preset)
CHAR_GRID_MS_K32 = 0.0048         # measured, exp017 (non-AR char-slot decode, K=32)


def hybrid_mean_latency_ms(f_copy: float, t_copy_ms: float,
                           t_graph_ms: float = GRAPH_DECODE_MS) -> float:
    """Mean per-concept latency when a fraction f_copy takes the copy channel."""
    return (1.0 - f_copy) * t_graph_ms + f_copy * t_copy_ms


def copy_fraction_ceiling(target_speedup: float, t_copy_ms: float,
                          t_graph_ms: float = GRAPH_DECODE_MS,
                          t_baseline_ms: float = SONAR_TEXT_DECODE_MS) -> float:
    """Largest copy-channel fraction f that keeps mean speedup >= target_speedup.
    1.0 if even the pure copy channel meets the target (non-binding ceiling)."""
    budget = t_baseline_ms / target_speedup
    if t_copy_ms <= budget:
        return 1.0
    if t_graph_ms >= budget:
        return 0.0
    return (budget - t_graph_ms) / (t_copy_ms - t_graph_ms)
